version: '3.7'

services:
  
  client:
    init: true
    depends_on:
      - authserver
    hostname: client
    build:
      context: oauth-client
#      network: host
    image: oauth2handson:client
    command: --check-caps false
    container_name: client
    ports:
    - "9091:52773"
    - "8081:1972"
    volumes:
    - .:/app

  resserver:
    init: true
    depends_on:
      - authserver
    hostname: resserver
    build:
      context: oauth-resource-server
#      network: host
    image: oauth2handson:resserver
    command: --check-caps false
    container_name: resourceserver
    ports:
    - "9092:52773"
    - "8082:1972"
    volumes:
    - .:/app

  authserver:
    init: true
    depends_on:
      - webserver

    hostname: authserver
    build:
      context: oauth-auth-server
      dockerfile: Dockerfile
#      network: host
    image: oauth2handson:authserver
    command: --check-caps false
    container_name: authserver
    ports:
    - "9093:52773"
    - "8083:1972"
    volumes:
    - .:/app

  webserver:
    hostname: webserver
    build:
      context: webserver
      dockerfile: Dockerfile
#     network: host
    image: oauth2handson:webserver
    container_name: webserver
    init: true
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./webserver:/webserver
    environment:
    - ISC_DATA_DIRECTORY=/webserver

 #       depends_on:
 #     - authserver
